# Generated by Django 2.1.5 on 2020-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200219_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
